language: python

dist: xenial

matrix:
    include:
#        - &python36
#          python: '3.6'
#          env: ORANGE="release"
#        - &python37
#          python: '3.7'
#          env: ORANGE="release"
        - &master
          python: '3.7'
          env: ORANGE="master"

cache:
    apt: true   # does not work for public repos
    directories:
        - $HOME/.cache/pip
        - $HOME/.ccache
        - $TRAVIS_BUILD_DIR/pyqt

before_cache:   # prevent logs from caching
    - rm -f $HOME/.cache/pip/log/debug.log

before_install:
    - source $TRAVIS_BUILD_DIR/.travis/util.sh
    - pip install -U setuptools pip wheel
    - pip install codecov
    # Orange requires numpy>=1.16 but cannot update it itself?
    - pip install -U numpy
    - mkdir -p /home/travis/.local/share/Orange  # create orange app dir

install:
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - pip install sip pyqt5==5.11.*
    - python setup.py develop   # assure version.py is present; required for imports

script:
    - XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" coverage run setup.py test

after_success:
    - codecov
