[tool.poetry]
name = "mobi"
version = "0.3.1"
description = "unpack unencrypted mobi files"
authors = ["Titusz Pan <tp@py7.de>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/iscc/mobi"
repository = "https://github.com/iscc/mobi"
keywords = ["mobi", "mobipocket", "unpack", "extract", "text"]

classifiers = [
    "Development Status :: 4 - Beta",
]

[tool.poetry.scripts]
mobiunpack = 'mobi.kindleunpack:main'

[tool.poetry.dependencies]
python = "^3.6"
loguru = "^0.4"

[tool.poetry.dev-dependencies]
pytest = "^5"
black = { version = "^19.10b0", python = "^3.6" }

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
