# Travis file for CI testing
---
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

script: make test

jobs:
  include:
    - stage: lint
      script: make lint
      python: "3.8"
    - stage: deploy
      script: skip
      python: "3.8"
      deploy:
        provider: pypi
        user: "__token__"
        password: $PYPI_TOKEN
        distributions: "sdist bdist_wheel"
        skip_existing: true
        on:
          tags: true


stages:
  - lint
  - test
  - deploy
