[package]
name = "staticrab-backend"
version = "0.0.3"
authors = ["vlada.kunc@gmail.com"]
edition = "2018"

[lib]
name = "staticrab_backend"
crate-type = ["cdylib"]
path = "src/lib.rs"


[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]


[dependencies]
numpy = ">= 0.8.0"
ndarray = ">= 0.13"
matrixmultiply = "0.2.0"
num-traits = "0.2.11"
rayon = ">=1.3.0"
clap = {version = ">=2.33.0", features = ["yaml"]}
staticrab-rust = {version= ">=0.0.2", path="../staticrab-rust"}
