
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-30T17:16:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a22f17bc4abc058e258ada3d0855510289b677d2",
 "version": "v2.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
