---
image: python:3.7.1

pipelines:
  default:
    - step:
        name: Run tests
        script:
          - pip install -r requirements.txt
          - python setup.py build
        caches:
          - pip
  branches:
    main:
      - step:
          name: Deploy to PyPi
          script:
            - pip install flit
            - flit publish
          caches:
            - pip
