
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-24T20:42:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "73ad2366215a153265036a5d4460d6c2c9c16676",
 "version": "0.0.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
