[tool.poetry]
name = "path-util"
version = "0.1.2"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]
readme = "README.md"
repository = "https://github.com/eyalev/path-util"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
