[tool.poetry]
name = "arcane-stackdriver"
version = "0.1.0"
description = "Override stackdriver client"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
google-cloud-error-reporting = "0.34.0"
# arcane-core = "1.0.0" (optional)

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
