language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false


env:
    global:
        - TOXENV=''
        - TOXARGS=''
        - TOXPOSARGS=''

        - TOX_CMD='tox --'
        - TOX_ARGS=''

matrix:

    include:
        # do the actual tests against dev version of POPPY

        # Do a coverage test in Python 3.
        - env: TOXENV='py38-poppydev-pysiafdev-cov'

        # Check for Sphinx doc build errors
        - env: TOXENV='docbuild' TOX_ARGS=''

        # Try Astropy development version
        - env: TOXENV='py38-astropydev-test'

        # Try minimum supported versions
        - env: TOXENV='py36-legacy36-test'

        # Try released POPPY
        - env: TOXENV='py37-stable-test'

    allow_failures:
        # Released POPPY and/or pySIAF may be missing new functionality used by dev WebbPSF
        - env: TOXENV='py37-stable-test'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install tox tox-conda>=0.2
    - pip install --user codecov

before_script:
    # Get WebbPSF data files (just a subset of the full 250 MB!) and set up environment variable
    - wget https://stsci.box.com/shared/static/qcptcokkbx7fgi3c00w2732yezkxzb99.gz -O /tmp/minimal-webbpsf-data.tar.gz
    - tar -xzvf /tmp/minimal-webbpsf-data.tar.gz
    - export WEBBPSF_PATH="${TRAVIS_BUILD_DIR}/webbpsf-data"

script:
   - conda info
   - $TOX_CMD $TOX_ARGS

after_success:
   - codecov

notifications:
  email:
  - mperrin@stsci.edu

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: McRW3+IUUn8m/wp/wop3tQax+pAgPhfaiDejbpQrQDMxWo2Uanyy/kcp7MO1MWeItmf/rPCcy3/LKD4EYG4/RU4rSrn/NjV8luYsM89Sti8vAmZ9yiC5u1mDLb0pknWt0KiL8se7pHz2myhg6ddkou44cYk3O9f8a6q/frygXExeOn7fsiZQCGX+PdyJQGVFnoOosHPRKk8kAXr2vlg+mBpEnGt+Pd2KorqIaz4Co6IaTE3VDf+Zo9mbiOsgY8CYbOhH0a3u3U5l12qUmCeQPw7+guJcy0zlBieiEjUB6aPN0VotRaLidc12N/pqZ0hXVVwgB/XKq0JJrECfsNQIxGDZCfKeadcwlFCiEki/zvvH7f2E5fuA4rAAej77tZC3AJXUxpBobv9Eed+MoLZCYq7F74CCuX6MbqUmoTtZdG75uRUfFf/mcTe3dy4cCuIrJG06/I+M0IUdyfCsFkE7HoXiSGJPcSvUsdI+lCyXYZC5l6d02n/v6rz8QTrQAbrveh5VSArj2XQCvNa0YiBz54eIzr9Fe3UQmVw8wlRdmNOcDo0LejwDYL44mm6MbX2VyPFyGqPRbe+NSSPC/LHdBCGEQX01HkmV3kmLFXnSIzpIbjJRzl+dRvN7CVSS3XL8efwPvqsmXReK+VnZ9IzMvYWboK1Bg4/Ri5PRSMKCWhc=
  on:
    branch: stable
    tags: true
  skip_existing: true
