
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-26T13:28:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4b0d2944d88fd8ed4d4301ba0ac7e905c50ff93",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
