
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-30T10:39:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "186ba7ed336ef80071e62462eb7ecf0589556895",
 "version": "0.8.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
