
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-29T14:16:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "11c36958e45dc94f51574fe661a6166e1ce81f55",
 "version": "0.1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
