protcol = "has-position"
doc = """
Daemons with this trait have one specific value that describes their current position.
This position can be set (using the set_position method).
In general, these daemons may not be able to reach exactly the set position.
The destination (get_destination) returns exactly the set position, while the position (get_position) returns the current actual position of the daemon.
These daemons should start motion and become busy when set_daemon is called.
They should release busy once they arrive as close as possible to the destination, and their position should not change until set_position is called again.
"""
requires = []

[state]
position.type = "number"
destination.type = "number"

[messages.get_destination]
doc = "Get current daemon destination."
returns = "number"

[messages.get_units]
doc = "Get units of daemon. These units apply to the position and destination fields."
response = {"type"="string"}

[messages.get_position]
doc = "Get current daemon position."
response = {"type"="float"}

[messages.set_position]
doc = "Give the daemon a new destination, and begin motion towards that destination."
request = [
  {"name"="position", "type"="float"}
]

[messages.set_relative]
doc = "Give the daemon a new destination relative to its current position. Daemon will immediately begin motion towards new destination. Returns new destination."
response = {"type"="float"}
request = [
  {"name"="distance", "type"="float"}
]
