[tool.poetry]
name = "globmatch_temp"
version = "0.1.1"
description = ""
authors = ["Damien Krystkiewicz <damien.krystkiewicz@gmail.com>"]

[tool.poetry.dependencies]
python = "^3"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
