name: nlpiaenv

channels:
  - conda-forge
  - defaults

dependencies:
  # - boto3
  # - conda-build
  - cython==0.29
  - gensim>=3.4.0,<3.7.0
  - jupyter>=1.0.0,<3.0.0
  - keras-applications>=1.0.6
  - keras-preprocessing>=1.0.5
  - keras>=2.2.4
  - matplotlib>=2.2.2,<2.3.0
  - nltk>=3.4.5,<3.5.0
  - numpy==1.14.5
  - opencv>=3.3.0,<3.5.0
  # - pandas
  - pandoc>=2.2.3,<3.0.0
  - pip>=18.0
  - plac>=0.9.6,<1.0.0
  - plotly==3.3.0
  - pyqt>=5.9.2,<6.0
  - pyscaffold>=3.1
  - python-levenshtein>=0.12.0
  - redis-py>=2.10.6
  - regex==2017.4.5
  - scipy>=1.1.0
  - spacy>=2.0.12
  - swig>=3.0.12
  - tensorflow>=1.13.1
  - tensorflow-hub>=0.4.0
  - theano==1.0.2

  - pip:
    - -r ../requirements/requirements-base.txt
