blue_dot_sessions = [
  "#c95656",
  "#c2536a",
  "#b1528e",
  "#9168aa",
  "#6c74b6",
  "#6c74b6",
  "#5d95aa",
  "#5d95aa",
  "#5daa97",
  "#bec25f",
  "#c2aa5b",
  "#ca936f"
]


[HSL]
  palette=[
    [0.0, 0.9, 0.5],
    [0.2, 0.9, 0.5],
    [0.4, 0.9, 0.5],
    [0.6, 0.9, 0.5],
    [0.8, 0.9, 0.5],
    [1.0, 0.9, 0.5]
  ]
  type="hsl"
