name: Release Docker container

on:
  push:
    tags: [ '*' ]

jobs:
  release-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push tag and latest
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: konstin2/maturin
        tag_with_ref: true
        tags: latest
