#########################################################################
###################### CerebralCortex Core Config #######################
#########################################################################
cc:
  debug: True # Setting this to True will log and print errors on console as well
  throw_exception: True #if this is set to True then application will get exceptions
  auth_token_expire_time: 40000 #seconds
  auth_encryption_key: "md@k&#8"
  log_files_path: "/tmp/"

#########################################################################
#                        NoSQL Storage                                  #
#########################################################################
nosql_storage: filesystem

filesystem:
  # in case of nosql_store=filesystem, provide directory path where all processed-data shall be stored
  filesystem_path: "/tmp/"

object_storage:
  object_storage_path: "/tmp/"

#########################################################################
#                          Relational Storage                           #
#########################################################################
relational_storage: mysql

mysql:
  host: 127.0.0.1 # change if MySQL is installed remotely
  port: 3306 # Change if MySQL is not using default port
  db_user: root # Change
  db_pass: pass # Change

  # Note: do not change following parameters if you don't know what you are doing
  database: cerebralcortex
  connection_pool_size: 1

#########################################################################
###################### Visualization Data Storage #######################
#########################################################################
visualization_storage: none

#########################################################################
#                          Data Provenance Storage                      #
#########################################################################
mprov: none

pennprov:
  host: http://127.0.0.1:8088
  user: demo
  password: demo
