release:
  method: github

mirrors:

  osf:
    method: osf
    project: q3bd6
    folder: distriploy

  neuropoly:
    method: rsync
    remote: exmakhina.com:/var/www/exmakhina.com/distriploy/

  academictorrents:
    method: academictorrents
    params:
      name: distriploy
      authors: distriploy team
      descr: "@article{title = {Distroploy}, author = {Distriploy authors}, abstract = {Distriploy is a small tool handling release deployment}}"
    add_other_mirror_urls: true

postrelease:
  add_mirror_urls: true
