# Generated by Django 3.0.7 on 2020-06-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200619_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boolean',
            old_name='boolean',
            new_name='boolean_field',
        ),
    ]
