# Generated by Django 3.0.7 on 2020-06-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200620_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boolean',
            old_name='boolean_field',
            new_name='boolean_field_one',
        ),
    ]
