protocol = "is-daemon"
doc = "Core trait common to all yaq daemons."
requires = []

[config]
port.type = "integer"
port.description = "TCP port for daemon to occupy."
serial.type = "string"
serial.default = "NULL"
serial.description = "Serial number for the particular device represented by the daemon"
make.type = "String"
make.default = "NULL"
model.type = "String"
model.default = "NULL"

[messages]

[messages.busy]
doc = "Returns true if daemon is currently busy."
response = {"type"="boolean"}

[messages.id]
doc = """
JSON object with information to identify the daemon, including name, kind, make, model, serial.
"""
response = {"name"="id", "type"="record", "fields"=[{"name"="value", "type"="string"}]}

[messages.get_config_filepath]
doc = """
String representing the absolute filepath of the configuration file on the host machine.
"""
response = {"type"="string"}

[messages.get_config]
doc = """
Full configuration for the individual daemon as defined in the TOML file.
This includes defaults and shared settings not directly specified in the daemon-specific TOML table.
"""
response = {"name"="config", "type"="record", "fields"=[{"name"="value", "type"="string"}]}

[messages.get_traits]
doc = "Get a full list of the daemon traits."
response = {"name"="traits", "type"="array", "items"="string"}

[messages.set_state]
doc = "Set daemon state. Accepts any subset of the state dictionary, dynamically."

[messages.shutdown]
doc = "Cleanly shutdown (or restart) daemon."
request = [
  {"name"="restart", "type"="boolean", "default"="false"},
]
