name = "is-sensor"
description = """
Daemons with the is-sensor trait are capable of measuring some unknown quantities.
Sensor daemons may have multiple channels if a single measurement returns multiple values.
"""
requires = []

[messages]

[messages.measure]
args.loop.type = "boolean"
response = {"type"="int"}
description = "Initiate a measurement. Returns integer, measurement ID."

[messages.get_measured]
returns = "dictionary name: value"
description = "Get most recent measured value. Additional key of measurement ID."

[messages.stop_looping]
description = "Stop looping measurement."

[messages.get_channel_names]
returns = "list of string"
description = "Get current channel names."

[messages.get_channel_shapes]
returns = "dictionary name: list of int"
description = "Get current channel shapes. If list is empty, channel is scalar."

[messages.get_channel_units]
returns = "dictionary name: units"
description = "Get current channel units."
