[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "yapapi"
version = "0.1.0"
description = "Hi-Level API for Golem The Next Milestone"
authors = ["Przemysław K. Rekucki <przemyslaw.rekucki@golem.network>"]
license = "LGPL-3.0-or-later"
classifiers = [
    "Development Status :: 1 - Planning",
    "Framework :: AsyncIO",
    "Topic :: System :: Distributed Computing"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.1"
aiohttp = "^3.6.2"
dataclasses = { version = "^0.7", python = ">=3.6, <3.7"}
ya-market = "^0.1.0"
urllib3 = "^1.25.9"

[tool.poetry.dev-dependencies]
setuptools = "black"
black = "^19.10b0"
pytest = "^5.4.3"
