from djangopost.views.ArticleCreateView import ArticleCreateView
from djangopost.views.ArticleDeleteView import ArticleDeleteView
from djangopost.views.ArticleDetailView import ArticleDetailView
from djangopost.views.ArticleListDashboard import ArticleListDashboard
from djangopost.views.ArticleListView import ArticleListView
from djangopost.views.ArticleUpdateView import ArticleUpdateView
from djangopost.views.CategoryCreateView import CategoryCreateView
from djangopost.views.CategoryDeleteView import CategoryDeleteView
from djangopost.views.CategoryDetailView import CategoryDetailView
from djangopost.views.CategoryListDashboard import CategoryListDashboard
from djangopost.views.CategoryUpdateView import CategoryUpdateView