
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-30T18:25:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ee817219c9da5b137d0e5981ac6dfd51315113a",
 "version": "0.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
