[tool.poetry]
name = "gui-util"
version = "0.1.5"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]

[tool.poetry.scripts]
gui = 'gui_util.cli:cli'

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
shell-util = "^0.1.3"
python-xlib = "^0.27"
ewmh = "^0.1.6"
dataclasses = { version = "^0.7", python = "~3.6" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
