[tool.poetry]
name = "autosocks"
version = "0.1.0"
description = ""
authors = ["Gerald <gera2ld@live.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"gera2ld.socks" = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
autosocks = "autosocks.__main__:main"

