
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-23T02:33:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e0cf9c8683d11528e01c8e3d7d63e179c6bd6f2",
 "version": "v2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
