[tool.poetry]
name = "poetry-test-6"
version = "0.1.0"
description = ""
authors = ["Peter Lin <Peter.Lin@nike.com>"]

[tool.poetry.dependencies]
python = "^2.7"
pendulum = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
