# coding: utf-8

"""
    pipelinecomponentapis.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kaistack.clients.openapi_clients.pipelinecomponents
from kaistack.clients.openapi_clients.pipelinecomponents.models.codegen_update_component_version_response import CodegenUpdateComponentVersionResponse  # noqa: E501
from kaistack.clients.openapi_clients.pipelinecomponents.rest import ApiException

class TestCodegenUpdateComponentVersionResponse(unittest.TestCase):
    """CodegenUpdateComponentVersionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CodegenUpdateComponentVersionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kaistack.clients.openapi_clients.pipelinecomponents.models.codegen_update_component_version_response.CodegenUpdateComponentVersionResponse()  # noqa: E501
        if include_optional :
            return CodegenUpdateComponentVersionResponse(
                success = True
            )
        else :
            return CodegenUpdateComponentVersionResponse(
        )

    def testCodegenUpdateComponentVersionResponse(self):
        """Test CodegenUpdateComponentVersionResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
