{% set data = load_setup_py_data() %}

package:
  name: hcrystalball
  version: {{ data['version'] }}

source:
   path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}  
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - numpy=1.18
    - pandas=1.0
    - scipy=1.4
    - scikit-learn=0.23
    - workalendar=10.1
    - matplotlib
  run:
    - python
    - numpy=1.18
    - pandas=1.0
    - scipy=1.4
    - scikit-learn=0.23
    - workalendar=10.1
    - matplotlib    

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
    - coveralls
  commands:
    - pytest    

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}

summary: {{ data['description'] }}    