# coding: utf-8

"""
    Nomad Envoy

    This is the API descriptor for the Nomad Envoy API, responsible for order creation and product lists.<br><br> Developed by <a href=\"https://samarkand.global\">Samarkand Global</a> in partnership with <a href=\"https://www.sf-express.com/cn/sc/\">SF Express</a><br><br> Install for node with <br>`npm install nomad_envoy_cli`<br><br> Install for python with <br>`pip install nomad-envoy-cli`<br>  # noqa: E501

    The version of the OpenAPI document: 1.40.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "nomad-envoy-cli"
VERSION = "1.40.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Nomad Envoy",
    author="OpenAPI Generator community",
    author_email="paul@samarkand.global",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Nomad Envoy"],
    install_requires=REQUIRES + ["querystring==0.1.0"],
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    This is the API descriptor for the Nomad Envoy API, responsible for order creation and product lists.&lt;br&gt;&lt;br&gt; Developed by &lt;a href&#x3D;\&quot;https://samarkand.global\&quot;&gt;Samarkand Global&lt;/a&gt; in partnership with &lt;a href&#x3D;\&quot;https://www.sf-express.com/cn/sc/\&quot;&gt;SF Express&lt;/a&gt;&lt;br&gt;&lt;br&gt; Install for node with &lt;br&gt;&#x60;npm install nomad_envoy_cli&#x60;&lt;br&gt;&lt;br&gt; Install for python with &lt;br&gt;&#x60;pip install nomad-envoy-cli&#x60;&lt;br&gt;  # noqa: E501
    """
)
