apiVersion: v1
kind: DeploymentConfig
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    name: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nitrate
        image: nitrate/nitrate:latest
        ports:
        - containerPort: 80
#   triggers:
#   - type: ConfigChange 
#   - imageChangeParams:
#       automatic: true
#       containerNames:
#       - nitrate-tcms
#       from:
#         kind: ImageStreamTag
#         name: nitrate/nitrate:latest
#     type: ImageChange  
#   strategy:
#     type: Rolling