[tool.poetry]
name = "pysamplespace"
packages = [
    { include = "samplespace" },
]
version = "1.0.3"
description = "SampleSpace is a cross-platform library for describing and sampling from random distributions."
authors = ["Coriander V. Pines <contact@corianderpines.org>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://gitlab.com/cvpines/pysamplespace"
repository = "https://gitlab.com/cvpines/pysamplespace"
documentation = "https://pysamplespace.readthedocs.io/en/latest/"
keywords = ["random", "distribution", "sampling", "simulation", "pcg"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Artistic Software",
    "Topic :: Games/Entertainment",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing"
]

[tool.poetry.dependencies]
python = "^3.7"
xxhash = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pyyaml = "^5.3"
toml = "^0.10.0"
coverage = "^5.1"
sphinx = "^3.0"
sphinx-rtd-theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
