
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-06-22T17:43:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "22a1afc18744f0f368f2d875fcbb6737fd048ff1",
 "version": "0.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
