[tool.poetry]
name = "pluto2npy"
version = "0.1.0"
license = "MIT"
readme = "README.rst"
repository = "https://gitlab.com/szs/pluto2npy/"
description = "Convert PLUTO output files to numpy npy files"
authors = ["Steffen Brinkmann <s-b@mailbox.org>"]
keywords = ["CFD", "conversion", "simulation", 'hydrodynamics', 'magnetohydrodynamics']
classifiers = ["Development Status :: 4 - Beta",
            "Intended Audience :: Science/Research",
            "License :: OSI Approved :: MIT License",
            "Programming Language :: Python :: 3",
            "Programming Language :: Python :: 3.6",
            "Programming Language :: Python :: 3.7",
            "Programming Language :: Python :: 3.8",
            "Topic :: Scientific/Engineering"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
p2n = 'pluto2npy.p2n:run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
