# Generated by Django 2.2.8 on 2020-01-29 16:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pgpy', '0002_auto_20200116_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='secret_blob',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
