[tool.poetry]
name = "blue-dot-sessions_gemscapes"
version = "1.8.0"
description = "Blue Dot Sessions Gemscape Generation"
authors = ["Dean Shaff <dean.shaff@gmail.com>"]
packages = [
    { include = "gemscapes" }
]
include = ["blue_dot_sessions.color.toml"]

[tool.poetry.dependencies]
python = "^3.6"
cython = "^0.29.19"
numpy = "^1.16"
toml = "^0.10.0"
eyeD3 = "^0.9.5"
pillow = "6.2.2"
pysndfile = "^1.4.3"
tqdm = "^4.45.0"
colour = "^0.1.5"
scikit-image = "^0.16.2"
pyclipper = "^1.1.0"

[tool.poetry.dev-dependencies]
matplotlib = "^3.2.1"
cairocffi = "^1.1.0"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
