[tool.poetry]
name = "pbwrap"
version = "1.2.1"
description = "Pastebin API Wrapper"
authors = ["Mikts <mikts94@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23"
aiohttp = "^3.6"
twine = "^3.1"
wheel = "^0.34.2"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
black = {git = "https://github.com/psf/black"}
pytest = "^5.3"
coverage = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
