[tool.black]
target-version = ['py35']
line-length = 119
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.eggs
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.github
  | _build
  | build
  | dist
)/
'''
