- job:
    name: python-barbicanclient-dsvm
    parent: legacy-dsvm-base
    run: playbooks/python-barbicanclient-dsvm/run.yaml
    post-run: playbooks/python-barbicanclient-dsvm/post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack-gate
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/python-barbicanclient

- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - python-barbicanclient-dsvm
    gate:
      jobs:
        - python-barbicanclient-dsvm
