# coding: utf-8

"""
    Honeywell

    This is an api to connect to the Honeywell backend  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import aliro_honeywell
from aliro_honeywell.models.inline_response2003_jobs import InlineResponse2003Jobs  # noqa: E501
from aliro_honeywell.rest import ApiException

class TestInlineResponse2003Jobs(unittest.TestCase):
    """InlineResponse2003Jobs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2003Jobs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = aliro_honeywell.models.inline_response2003_jobs.InlineResponse2003Jobs()  # noqa: E501
        if include_optional :
            return InlineResponse2003Jobs(
                cost = 1.337, 
                job = '0', 
                machine = '0', 
                name = '0', 
                result_date = '0', 
                submit_date = '0'
            )
        else :
            return InlineResponse2003Jobs(
        )

    def testInlineResponse2003Jobs(self):
        """Test InlineResponse2003Jobs"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
