
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f0b15f1a8db7635b492427fa8484a633d505b456",
 "version": "0.11.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
