# Generated by Django 3.0.6 on 2020-05-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandboxes', '0004_auto_20200526_1318'),
        ('genviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
