language: python
cache: pip
dist: xenial

matrix:
  include:
    - name: Check flake8
      python: 3.7
      env: TOXENV=flake8
    - name: Check black formatting
      python: 3.7
      env: TOXENV=black
    - name: Check license headers
      python: 3.7
      env: TOXENV=license

install:
  - pip install tox

script:
  - tox
