[tool.poetry]
name = "topdown"
version = "0.2.1"
description = ""
authors = ["Kevin Schiroo <kjschiroo@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
