
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-30T17:51:07+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ec7a2a948de63f3f789c39d0e5ff289c871dfc6",
 "version": "0.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
