[tool.poetry]
name = "ddv-printing"
version = "0.1.0"
description = ""
authors = ["Davide Vitelaru <davide@vitelaru.com>"]

packages = [
  { include = "ddv", from="src"}
]

[tool.poetry.dependencies]
python = "^3.7"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^19.10b0"
invoke = "^1.4.1"

[tool.poetry.scripts]
mypy = "tasks:mypy"
flake8 = "tasks:flake8"
check = "tasks:check"
examples = "tasks:examples"
# test = "tasks:test"
# watch = "tasks:watch"
# docs = "tasks:docs"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
