# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
# virtualenv:
#   system_site_packages: true
env:
  matrix:
    # - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true" COVERALLS="false"
    # - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false" COVERALLS="false"
    # - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false" COVERALLS="false"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true" COVERALLS="true" BOTO_CONFIG="/dev/null"
    # - DISTRIB="ubuntu" PYTHON_VERSION="3.5" COVERAGE="true" COVERALLS="true"
addons:
  apt:
    packages:
      - git
      - python-pip
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - source tests/travis_install.sh
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - git config --global user.email "travis@totalgood.com"
  - git config --global user.name "pugnlp Travis Tests"
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
