
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-23T16:13:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "43937bf5a00511cabc9dc875a3f670d51a5f54da",
 "version": "0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
