channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- ipython>=6.1.0
- python>=3.6
- pip>=19.0.0
- matplotlib>=2.0.2
- astropy>=3.0
- scikit-image>=0.13.0
- scikit-learn>=0.19.0
- scipy>=1.0.0
- sphinx>=1.7.5
- jupyter>=1.0.0
- yaml>=0.1.7
- pyyaml>=3.12
- nose>=1.3.7
- cython>=0.28.2
- astroquery>=0.3.7
- photutils>=0.4
- pyregion>=2.0
- crds>=7.1.5
- drizzlepac>=2.2.2
- hstcal>=2.0.0
- pysynphot>=0.9.12
- stwcs>=1.4.0
- wfc3tools>=1.3.4
- shapely>=1.6.4
- descartes>=1.0.2
- boto3>=1.7.51
- pip:
  - peakutils>=1.0.3
  - extinction>=0.3.0
  - git+https://github.com/gbrammer/sep.git
  - git+https://github.com/gbrammer/pyia.git
  - git+https://github.com/gbrammer/reprocess_wfc3.git
  - git+https://github.com/gbrammer/eazy-py.git
  - git+https://github.com/gbrammer/tristars.git
  - git+https://github.com/gbrammer/mastquery.git

