channels:
- astropy
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- astroquery>=0.3.7
- pyregion>=2.0
- astropy>=3.0
- curl>=7.55.1
- cython>=0.28.2
- geos>=3.5.0
- ipython>=6.1.0
- jupyter>=1.0.0
- jupyter_client>=5.1.0
- jupyter_console>=5.2.0
- jupyter_core>=4.3.0
- matplotlib>=2.0.2
- lxml>=4.0
- numpy>=1.14.2
- numpydoc>=0.7.0
- pip>=9.0.1
- pkg-config>=0.29.2
- pkgconfig>=1.2.2
- pkginfo>=1.4.1
- python>=3.5.4
- pytest>=3.2.1
- pyyaml>=3.12
- scikit-image>=0.13.0
- scikit-learn>=0.19.0
- scipy>=0.19.1
- shapely>=1.6.4
- tk>=8.6.7
- urllib3>=1.22
- yaml>=0.1.7
- acstools>=2.0.9
- appdirs>=1.4.0
- asdf>=1.2.1
- cfitsio>=3.370
- crds>=7.1.5
- d2to1>=0.2.12
- decorator>=4.0.9
- drizzle>=1.5
- drizzlepac>=2.2.2
- ds9>=7.5
- fftw>=3.3.4
- fitsblender>=0.3.2
- fitsverify>=4.18
- gwcs>=0.8.0
- hstcal>=2.0.0
- photutils>=0.4
- py-expression-eval>=0.3.4
- pyds9>=1.9.0.dev
- pyfftw>=0.9.2
- pyqt>=5.6.0
- qt>=5.6.2
- qtconsole>=4.3.0
- qtpy>=1.3.1
- pyqtgraph>=0.10.0
- pysynphot>=0.9.12
- pytools>=2016.1
- reftools>=1.7.4
- stginga>=0.2.1
- stsci>=3.0.0
- stsci-data-analysis>=2.0.2
- stsci-hst>=3.0.0
- stsci.convolve>=2.2.1
- stsci.distutils>=0.3.8
- stsci.image>=2.3.0
- stsci.imagemanip>=1.1.2
- stsci.imagestats>=1.4.1
- stsci.ndimage>=0.10.1
- stsci.numdisplay>=1.6.1
- stsci.skypac>=0.9.5
- stsci.sphere>=0.2
- stsci.sphinxext>=1.2.2
- stsci.stimage>=0.2.1
- stsci.tools>=3.4.12
- stwcs>=1.4.0
- wfc3tools>=1.3.4
- pip:
  - descartes>=1.0.2
  - peakutils>=1.0.3
  - extinction>=0.3.0
  - sep>=1.0.1
  - git+https://github.com/cmccully/lacosmicx.git
  - git+https://github.com/gbrammer/pyia.git
  - git+https://github.com/gbrammer/reprocess_wfc3.git
  - git+https://github.com/gbrammer/eazy-py.git
  - git+https://github.com/gbrammer/tristars.git
  - git+https://github.com/gbrammer/mastquery.git

