# specify the language and which version
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install -U pip
  - pip install codecov

install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install

# Runs test with coverage
script:
  - coverage run setup.py test

# Push the result to
after_success:
  - codecov

# deploy to PyPI
deploy:
  provider: pypi
  twine_version: 1.13.0
  skip_existing: true
  user: twomagpi
  password:
    secure: S+o0vhiAGM3qto2tQ8xoozMY3JuhDTlynzjMK2AyRMrWWI0Jvbp9u6TebD3zT3TNh/341t6JLY7VPj8KOam/7LzmpI56ouSyTKKHH7Uk2L2ZuJ4dPm4mS0htO26YBYUtjBpyc55VOmVxqUMXo3iym0jQ+uukrWrr+fY3wTTl1rn+RU5wdoQ+1Z9hi+txo2i24tGi9RCzRr5yCX88Q++MFtlNs2/Q4AtR9oQHY5muiPtlbxd1/JtmK43doxsUc+v0A+RJFpDMmURsUt+zoUeSm8Xz65EP9vjGL03YCn+SUp/2Iidfk3GLaBIDvNxKk6XB9njm6V+bXPpzgsM5fzFJ3XtXp3hoIcMlwoa03Hn3fGUw/W/KKsvJaPBDnjZ9qK2gHBNQuz5jbK/ijNuSuZWQvInGhA5Tt/6DOJwX/Q2d0H4hENwZKs5MnY+RXm6VDRJYnImyQLCW1HsxJa/q/2hTpOvlDHCWJNwWB59BTVOxRsW1gKVgiaF5K9hWd5x1DJvnxG15wNey/STOx+8bpaX7DPfZmqqGqbDNnCTKr2+X3EfTqglOWWM20fB9BY62GuvXPNS3/60aKXZfn7z7eI19b+0KMx2wHlnsP7oQmAQS4XK2wMOs3pD8iQzd/4jIVLa+k3YSYfhb0mKxJBkQtd+1s2GtoaHWnNRlpCUlwv1OU38=
  on:
    tags: true
    python: 3.7