
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-26T11:32:21+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "5189a858fa8bc0769d6c95d8f41bbb85ace814c8",
 "version": "3.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
