
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-27T20:22:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f55a4a2b68fa65e56a28baeb7f44122fdeca7e7",
 "version": "0.45a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
