# Autogenerated by Astropy-affiliated package pyvo's setup.py on 2020-06-26 21:44:31 UTC
from __future__ import unicode_literals
import datetime

version = "1.1"
githash = "cfbd8f6a24d83f0ae9b0b6a61c30c66bf5d09d7e"


major = 1
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 6, 26, 21, 44, 31)
debug = False

astropy_helpers_version = "3.2.1"
