MAJOR_VERSION = '1.2'
MINOR_REVISION = 1
if MINOR_REVISION > 0:
 VERSION = MAJOR_VERSION + '.' + "%s" % MINOR_REVISION
else:
 VERSION = MAJOR_VERSION

BASE_REVISION = VERSION 
RELEASE_NAME = "Valentina"
