# Generated by Django 3.0.4 on 2020-03-26 15:19

import ai_kit_file_management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="if no name is given the filename will be taken",
                        max_length=255,
                    ),
                ),
                ("size", models.IntegerField()),
                ("format", models.CharField(max_length=50, null=True, blank=True)),
                ("upload_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "file",
                    models.FileField(
                        upload_to=ai_kit_file_management.models.generate_unique_file_name
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
