name: Chisel3 Jar Package CI
language: python
script:
  - make prepare
  - python setup.py bdist_wheel
before_deploy:
  - export FILE=$(ls dist/*.whl)
  - echo "deploying $FILE to GitHub releases"
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: $FILE
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    username: $PYPI_NAME
    password: $PYPI_PW
    skip_cleanup: true
    on:
      tags: true
