---
name: Create stand-alone executable
on:
  push:
    tags:
    - v*
jobs:
  freeze:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Set up caching for Rust
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install PyOxidizer
      run: |
        cargo install pyoxidizer
    - name: Build instawow and copy into 'dist' directory
      run: |
        mkdir -p dist
        pyoxidizer build --release | tee >(cp $(tail -n 1 | cut -c 23-) dist/instawow)
    - name: Rename binary on Windows
      if: matrix.os == 'windows-latest'
      run: |
        mv dist/instawow dist/instawow.exe
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: instawow-${{ matrix.os }}
        path: dist/instawow*
