[build-system]
requires = [
    "setuptools >= 36.4",
    "wheel",
    "setuptools_scm >= 2.1",
    "cython >= 0.28.1",
    "scikit-build >= 0.9.0",
    "cmake",
    "ninja",
]
build-backend = "setuptools.build_meta"
