[tool.poetry]
name = "apex-legends-voicelines"
version = "0.1.0"
description = ""
authors = ["Justine Kizhakkinedath <justine@kizhak.com>"]

include = [
  "apex_legends_voicelines/assets/*"
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.poetry.scripts]
apex-voicelines = 'apex_legends_voicelines.__main__:main'
