[tool.poetry]
name = "pi-team-generic-es-client"
version = "1.1.2"
description = ""
authors = ["David Diks (DDQ) <david.diks@mn.nl>"]
license = "MIT"
packages = [
    {include  = "generic_elasticsearch"}
]

[tool.poetry.dependencies]
python = "^3.6"
urllib3 = "^1.25.9"
six = "^1.15.0"
certifi = "^2020.4.5"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
