---

owner: cust000

family: 'internal_id'
family_name: '643594'
samples:
  - analysis_type: wes
    sample_id: ADM1059A2a
    capture_kit: Agilent_SureSelectCRE.V1
    father: ADM1059A1a
    mother: ADM1059A3a
    sample_name: NA12882a
    phenotype: affected
    sex: male
    expected_coverage: 30

  - analysis_type: wes
    sample_id: ADM1059A1a
    capture_kit: Agilent_SureSelectCRE.V1
    father: '0'
    mother: '0'
    sample_name: NA12877a
    phenotype: unaffected
    sex: male
    expected_coverage: 30

  - analysis_type: wes
    sample_id: ADM1059A3a
    capture_kit: Agilent_SureSelectCRE.V1
    father: '0'
    mother: '0'
    sample_name: NA12878
    phenotype: unaffected
    sex: female
    expected_coverage: 30

vcf_snv: scout/demo/643594_no_var.clinical.vcf.gz

madeline: scout/demo/madeline.xml

peddy_ped: scout/demo/643594a.peddy.ped
peddy_ped_check: scout/demo/643594a.ped_check.csv
peddy_sex_check: scout/demo/643594a.sex_check.csv

delivery_report: scout/demo/delivery_report.html

default_gene_panels: [panel1]
gene_panels: [panel1]

# meta data
rank_model_version: '1.20'
rank_score_threshold: -100
analysis_date: 2016-10-12 14:00:46
human_genome_build: 37
