name = "is-sensor"
doc = """
Daemons with the is-sensor trait are capable of measuring some unknown quantities.
Sensor daemons may have multiple channels if a single measurement returns multiple values.
"""
requires = []

[messages]

[messages.measure]
doc = "Initiate a measurement. Returns integer, measurement ID."
request = [
  {"name"="loop", "type"="boolean"}
]
response = "int"

[messages.get_measured]
doc = "Get most recent measured value. Additional key of measurement ID."
response.type = "map"
response.values = "float"

[messages.stop_looping]
doc = "Stop looping measurement."

[messages.get_channel_names]
doc = "Get current channel names."
response.type = "array"
response.items = "string"

[messages.get_channel_shapes]
doc = "Get current channel shapes. If list is empty, channel is scalar."
response.type = "map"
response.values = {"type"="array", "items"="int"}

[messages.get_channel_units]
doc = "Get current channel units."
response.type = "map"
response.values = ["null", "string"]
