[tool.poetry]
name = "k0d_expert"
version = "0.0.1b"
description = "Cli для школы k0d.expert"
authors = ["Nikolay Baryshnikov <root@k0d.ru>"]
packages=[
    { include = "package" },
]
license="MIT"
readme="README.md"
homepage="https://k0d.expert"
repository="https://github.com/p141592/k0d_expert_cli"
keywords=["cli", "k0d", "education"]
classifiers=[
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Natural Language :: Russian",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
