
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-25T05:42:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a08d6c6b939af17672ae36e83c79dd9170fefb65",
 "version": "0.3.6.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
