[tool.poetry]
name = "gelfguru"
version = "0.1.1"
description = "Loguru extension for log in GELF payload format."
authors = ["Carlos Neto <carlos.santos110@fatec.sp.gov.br>"]
license = "Apache-2.0"
readme = "README.md"
homepage = ""
documentation = ""
classifiers = [ 
    "Topic :: Internet :: Log Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
loguru = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
