# coding: utf-8

"""
    workflowapis.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kaistack.clients.openapi_clients.workflow.configuration import Configuration


class CodegenArtifactMeta(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'run_id': 'str',
        'path': 'str',
        'type': 'str',
        'properties': 'dict(str, str)'
    }

    attribute_map = {
        'run_id': 'runId',
        'path': 'path',
        'type': 'type',
        'properties': 'properties'
    }

    def __init__(self, run_id=None, path=None, type=None, properties=None, local_vars_configuration=None):  # noqa: E501
        """CodegenArtifactMeta - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._run_id = None
        self._path = None
        self._type = None
        self._properties = None
        self.discriminator = None

        if run_id is not None:
            self.run_id = run_id
        if path is not None:
            self.path = path
        if type is not None:
            self.type = type
        if properties is not None:
            self.properties = properties

    @property
    def run_id(self):
        """Gets the run_id of this CodegenArtifactMeta.  # noqa: E501


        :return: The run_id of this CodegenArtifactMeta.  # noqa: E501
        :rtype: str
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this CodegenArtifactMeta.


        :param run_id: The run_id of this CodegenArtifactMeta.  # noqa: E501
        :type: str
        """

        self._run_id = run_id

    @property
    def path(self):
        """Gets the path of this CodegenArtifactMeta.  # noqa: E501


        :return: The path of this CodegenArtifactMeta.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this CodegenArtifactMeta.


        :param path: The path of this CodegenArtifactMeta.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def type(self):
        """Gets the type of this CodegenArtifactMeta.  # noqa: E501


        :return: The type of this CodegenArtifactMeta.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CodegenArtifactMeta.


        :param type: The type of this CodegenArtifactMeta.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def properties(self):
        """Gets the properties of this CodegenArtifactMeta.  # noqa: E501


        :return: The properties of this CodegenArtifactMeta.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this CodegenArtifactMeta.


        :param properties: The properties of this CodegenArtifactMeta.  # noqa: E501
        :type: dict(str, str)
        """

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodegenArtifactMeta):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CodegenArtifactMeta):
            return True

        return self.to_dict() != other.to_dict()
