[tool.poetry]
name = "ViteezyTool"
version = "0.1.5"
description = "Custom tool for Viteezy to generate customized word documents from an excel database"
authors = ["sander <sander@rolisa.nl>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
xlrd = "^1.2.0"
docxtpl = "^0.9.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
vit-tool = "viteezytool.app:run"