
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-25T15:02:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef33cae7fb51ab8fadd64a8f3637d926e5dfbcd8",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
