[tool.poetry]
name = "input-util"
version = "0.1.2"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
is-url = "^0.1.2"
file-util = "^0.1.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
