name: Generate coverage report

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Install FFmpeg
      run: |
        sudo apt-get install ffmpeg
    
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ always() }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate coverage report
      run: |
        pip install pytest pytest-cov h5py pandas tqdm
        cd tests
        export NUMBA_DISABLE_JIT=1
        export MPLBACKEND="agg"
        pytest --cov-report xml:report_coverage.xml --cov=pde ..
        
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./tests/report_coverage.xml
        yml: ./codecov.yml
        flags: unittests
        name: codecov-pydev
        fail_ci_if_error: true
