
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-27T17:14:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "50d0facc9bab372a6810bc8d97cce08d683ff32e",
 "version": "0.10rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
