{% set data = load_setup_py_data() %}

package:
  name: hcrystalball
  version: {{ data.get('version')}}

source:
   path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}  
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - numpy x.x      
    - pandas =1.0
    - scipy =1.4
    - scikit-learn =0.23
    - workalendar =10.1
    - matplotlib 
    - git
  run:
    - python
    - numpy x.x
    - pandas =1.0
    - scipy =1.4
    - scikit-learn =0.23
    - workalendar =10.1
    - matplotlib
    - git

test:
  requires:
    - pytest
    - pytest-cov        
  commands:
    - pytest    

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}

summary: {{ data.get('description') }}    
