stages:
  - test
  - deploy
  - validate

Test:
  stage: test
  image: python:3.7
  only:
    - pushes
  before_script:
    - pip install --editable .
    - pip install pytest
  script:
    - pytest

Publish on PyPI:
  stage: deploy
  image: python:3.7
  only:
    - tags
  tags:
    - dbnomics-data-model
  before_script:
    - pip install twine
    - python setup.py sdist bdist_wheel
  variables:
    TWINE_USERNAME: cbenz
    # TWINE_PASSWORD: # Secret variable, see project CI settings.
  script:
    - twine upload dist/*
  environment:
    name: PyPI
    url: https://pypi.org/project/dbnomics-data-model/$CI_COMMIT_TAG

Validate:
  stage: validate
  except:
    - pushes
  tags:
    - ioke-shell
  # variables:
  #   PROVIDER_SLUG: Will be defined by each fetcher via the webhook.
  script:
    - echo "Validating provider ${PROVIDER_SLUG}..."
    - bash -x ~/dbnomics-git-tools/clone-or-update-storage.sh ~/json-data ${PROVIDER_SLUG}
    - source ~/virtualenvs/dbnomics-data-model/bin/activate
    - pip install -e .
    - dbnomics-validate --bare-repo-fallback ~/json-data/${PROVIDER_SLUG}-json-data
