[tool.poetry]
name = "print-pretty"
version = "0.1.1"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]
readme = "README.md"
repository = "https://github.com/eyalev/print-pretty"

[tool.poetry.scripts]
print-pretty = "print_pretty.cli:cli"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
input-util = "^0.1.2"
yapf = "^0.30.0"
pyyaml = "^5.3.1"
print-dict = "^0.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
