[tool.poetry]
name = "arcane-date"
version = "0.1.0"
description = "A package to work with dates"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
# arcane-core = "1.0.0" (optional)

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
