
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-02T17:27:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "184d322b46a59cd8ba3a53e7ca1ed02dae9fd2e0",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
