
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-24T15:30:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6e4fc0f146e2449dd00db24748a42bed4923e0b",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
