[tool.poetry]
name = "cfg-cli"
version = "0.1.28"
description = "Command-line tool for Cofactor Genomics' products and services."
authors = ["Alex Bode <alex_bode@cofactorgenomics.com>"]
license = "MIT"

packages = [
    { include="cfg_cli", from="." },
]

[tool.poetry.dependencies]
python = "^3.4"
requests = "^2.23.0"
python-jose = "^3.1.0"
fire = "^0.2.1"
tabulate = "^0.8.7"
boto3 = "^1.14.11"
prompt-toolkit = "^3.0.5"
importlib-metadata = "^1.7.0"

[tool.poetry.dev-dependencies]
requests = "^2.23.0"
python-jose = "^3.1.0"
fire = "^0.2.1"
pytest = "^4.6"
coverage = "^5.0.3"
black = "^19.10b0"
isort = "^4.3.21"
tabulate = "^0.8.7"
boto3 = "^1.14.11"
prompt-toolkit = "^3.0.5"

[tool.poetry.scripts]
prism = "cfg_cli.prism_cli:wrapper"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# ~/.poetry/bin/poetry publish --username <username> --password <password> --build

