---
# Schema for CDN definitions dataset.
#
# This schema is used within autotests to ensure that every published
# revision of the dataset matches the expected structure.
#
# Check the dataset itself for explanatory comments on each field.

$schema: http://json-schema.org/draft-07/schema#
$id: http://release-engineering.github.io/cdn-definitions/schema.json


definitions:

  absolute_path:
    type: string
    pattern: "^/"

  path_alias:
    type: object
    properties:
      src:
        $ref: "#/definitions/absolute_path"
      dest:
        $ref: "#/definitions/absolute_path"
    requiredProperties:
    - src
    - dest
    additionalProperties: false

  path_alias_list:
    type: array
    items:
      $ref: "#/definitions/path_alias"
    uniqueItems: true


type: object
properties:

  version:
    type: string
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"

  rhui_alias:
    $ref: "#/definitions/path_alias_list"

  origin_alias:
    $ref: "#/definitions/path_alias_list"

requiredProperties:
- version
- rhui_alias
- origin_alias

additionalProperties: false
