#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['das_iboot']

package_data = \
{'': ['*']}

setup(name='das_iboot',
      version='0.1',
      description='Universal boot-loader for iDevices',
      author='Rick Mark',
      author_email='rickmark@guardianapp.com',
      url='https://github.com/GuardianFirewall/das-iboot',
      packages=packages,
      package_data=package_data,
     )
