[tool.poetry]
name = "fn_graph"
version = "0.14.2"
description = "Manage, maintain and reuse complex function graphs without the hassle."
authors = ["James Saunders <james@businessoptics.biz>"]
license = "MIT"
readme = "README.md"
documentation = "https://fn-graph.readthedocs.io/"
repository = "https://github.com/BusinessOptics/fn_graph"
homepage = "https://github.com/BusinessOptics/fn_graph"

[tool.poetry.dependencies]
python = "^3.7"
networkx = "^2.4"
graphviz = "^0.13.2"
littleutils = "^0.2.1"
# below `extras`. They can be opted into for examples.
seaborn = { version = "*", optional = true }
statsmodels = { version = "*", optional = true }
matplotlib = { version = "*", optional = true }
sklearn = { version = "*", optional = true }
plotly = { version = "*", optional = true }
pandas = { version = "*", optional = true }
yfinance = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
black = { version = "^18.3-alpha.0", allow-prereleases = true }
pytest = "^5.3"
sphinx = "^2.2"
mkdocs = "^1.0"
sphinx_rtd_theme = "^0.4.3"
recommonmark = "^0.6.0"
fn_deps = "^0.1.0"

[tool.poetry.extras]
examples = [
    "seaborn",
    "statsmodels",
    "matplotlib",
    "sklearn",
    "plotly",
    "pandas",
    "yfinance"
]

[tool.dephell.main]
from = { format = "poetry", path = "pyproject.toml" }
to = { format = "setuppy", path = "setup.py" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
