[tool.poetry]
name = "cs_django_thumbnails"
version = "0.3.3"
description = "A simple Django app to manage image/photo thumbnails. Supports remote/cloud storage systems like Amazon S3."
authors = ["Leopoldo Parra <lparra.dev@gmail.com>"]
license = "MIT"

packages = [
    { include="thumbnails", from="." },
]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.7"
shortuuid = "^1.0.1"
da-vinci = "^0.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
