environment:

  SUBUNIT: 0

  matrix:
    - python: 27
    - python: 27-x64
    - python: 35
    - python: 35-x64
    - python: 36
    - python: 36-x64
    - python: 37
    - python: 37-x64
    - python: 38
    - python: 38-x64
    - { python: 27, SUBUNIT: 1 }
    - { python: 27-x64, SUBUNIT: 1 }
    - { python: 35, SUBUNIT: 1 }
    - { python: 35-x64, SUBUNIT: 1 }
    - { python: 36, SUBUNIT: 1 }
    - { python: 36-x64, SUBUNIT: 1 }
    - { python: 37, SUBUNIT: 1 }
    - { python: 37-x64, SUBUNIT: 1 }
    - { python: 38, SUBUNIT: 1 }
    - { python: 38-x64, SUBUNIT: 1 }

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - python -m pip install -U setuptools pip
  # NB: pip install -e .[test] fails for obscure namespace package reasons
  - pip install -U .[test]
  - if %SUBUNIT%==1 pip install -U .[subunit]

build: false

test_script:
  - python setup.py -q test -q

on_success:
  - echo Build succesful!
