site_name: pytest_cases
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-pytest-cases
docs_dir: .
site_dir: ../site
nav:
    - Home: index.md
    - Usage details:
        - Overview: usage.md
        - Basics: usage/basics.md
        - Intermediate: usage/intermediate.md
        - Advanced: usage/advanced.md
    - API reference: api_reference.md
    - Changelog: changelog.md
theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true