# Generated by Django 2.2.8 on 2020-01-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pgpy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='encrypters',
            field=models.ManyToManyField(related_name='restorable_identities', to='django_pgpy.Identity'),
        ),
    ]
