# Generated by Django 2.2.8 on 2020-02-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pgpy', '0004_auto_20200129_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestkeyrecovery',
            name='hash_info',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
