# Generated by Django 2.2.8 on 2020-02-03 16:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pgpy', '0006_auto_20200203_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestkeyrecovery',
            name='secret_blob',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
