# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkSegmentBonesInMicroCTFilterPython
else:
    import _itkSegmentBonesInMicroCTFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkSegmentBonesInMicroCTFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkSegmentBonesInMicroCTFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.itkImageToImageFilterAPython
import itk.itkVectorImagePython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.itkIndexPython
import itk.itkSizePython
import itk.itkOffsetPython
import itk.itkImagePython
import itk.itkCovariantVectorPython
import itk.itkVectorPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.itkFixedArrayPython
import itk.vnl_vector_refPython
import itk.itkRGBPixelPython
import itk.itkPointPython
import itk.itkMatrixPython
import itk.vnl_matrix_fixedPython
import itk.itkImageRegionPython
import itk.ITKCommonBasePython
import itk.itkRGBAPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkVariableLengthVectorPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterCommonPython

def itkSegmentBonesInMicroCTFilterISS3ISS3_New():
    return itkSegmentBonesInMicroCTFilterISS3ISS3.New()

class itkSegmentBonesInMicroCTFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    r"""Proxy of C++ itkSegmentBonesInMicroCTFilterISS3ISS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3___New_orig__)
    Clone = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3_Clone)
    GetCorticalBoneThickness = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3_GetCorticalBoneThickness)
    SetCorticalBoneThickness = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3_SetCorticalBoneThickness)
    __swig_destroy__ = _itkSegmentBonesInMicroCTFilterPython.delete_itkSegmentBonesInMicroCTFilterISS3ISS3
    cast = _swig_new_static_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3_cast)

    def New(*args, **kargs):
        """New() -> itkSegmentBonesInMicroCTFilterISS3ISS3

        Create a new object of the class itkSegmentBonesInMicroCTFilterISS3ISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkSegmentBonesInMicroCTFilterISS3ISS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkSegmentBonesInMicroCTFilterISS3ISS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkSegmentBonesInMicroCTFilterISS3ISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkSegmentBonesInMicroCTFilterISS3ISS3 in _itkSegmentBonesInMicroCTFilterPython:
_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3_swigregister(itkSegmentBonesInMicroCTFilterISS3ISS3)
itkSegmentBonesInMicroCTFilterISS3ISS3___New_orig__ = _itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3___New_orig__
itkSegmentBonesInMicroCTFilterISS3ISS3_cast = _itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3ISS3_cast


def itkSegmentBonesInMicroCTFilterISS3IUC3_New():
    return itkSegmentBonesInMicroCTFilterISS3IUC3.New()

class itkSegmentBonesInMicroCTFilterISS3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUC3):
    r"""Proxy of C++ itkSegmentBonesInMicroCTFilterISS3IUC3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3___New_orig__)
    Clone = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3_Clone)
    GetCorticalBoneThickness = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3_GetCorticalBoneThickness)
    SetCorticalBoneThickness = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3_SetCorticalBoneThickness)
    __swig_destroy__ = _itkSegmentBonesInMicroCTFilterPython.delete_itkSegmentBonesInMicroCTFilterISS3IUC3
    cast = _swig_new_static_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3_cast)

    def New(*args, **kargs):
        """New() -> itkSegmentBonesInMicroCTFilterISS3IUC3

        Create a new object of the class itkSegmentBonesInMicroCTFilterISS3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkSegmentBonesInMicroCTFilterISS3IUC3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkSegmentBonesInMicroCTFilterISS3IUC3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkSegmentBonesInMicroCTFilterISS3IUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkSegmentBonesInMicroCTFilterISS3IUC3 in _itkSegmentBonesInMicroCTFilterPython:
_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3_swigregister(itkSegmentBonesInMicroCTFilterISS3IUC3)
itkSegmentBonesInMicroCTFilterISS3IUC3___New_orig__ = _itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3___New_orig__
itkSegmentBonesInMicroCTFilterISS3IUC3_cast = _itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUC3_cast


def itkSegmentBonesInMicroCTFilterISS3IUS3_New():
    return itkSegmentBonesInMicroCTFilterISS3IUS3.New()

class itkSegmentBonesInMicroCTFilterISS3IUS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUS3):
    r"""Proxy of C++ itkSegmentBonesInMicroCTFilterISS3IUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3___New_orig__)
    Clone = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3_Clone)
    GetCorticalBoneThickness = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3_GetCorticalBoneThickness)
    SetCorticalBoneThickness = _swig_new_instance_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3_SetCorticalBoneThickness)
    __swig_destroy__ = _itkSegmentBonesInMicroCTFilterPython.delete_itkSegmentBonesInMicroCTFilterISS3IUS3
    cast = _swig_new_static_method(_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3_cast)

    def New(*args, **kargs):
        """New() -> itkSegmentBonesInMicroCTFilterISS3IUS3

        Create a new object of the class itkSegmentBonesInMicroCTFilterISS3IUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkSegmentBonesInMicroCTFilterISS3IUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkSegmentBonesInMicroCTFilterISS3IUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkSegmentBonesInMicroCTFilterISS3IUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkSegmentBonesInMicroCTFilterISS3IUS3 in _itkSegmentBonesInMicroCTFilterPython:
_itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3_swigregister(itkSegmentBonesInMicroCTFilterISS3IUS3)
itkSegmentBonesInMicroCTFilterISS3IUS3___New_orig__ = _itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3___New_orig__
itkSegmentBonesInMicroCTFilterISS3IUS3_cast = _itkSegmentBonesInMicroCTFilterPython.itkSegmentBonesInMicroCTFilterISS3IUS3_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def segment_bones_in_micro_ct_filter(*args, **kwargs):
    """Procedural interface for SegmentBonesInMicroCTFilter"""
    import itk
    instance = itk.SegmentBonesInMicroCTFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def segment_bones_in_micro_ct_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.SegmentBonesInMicroCTFilter, itkTemplate.itkTemplate):
        filter_object = itk.SegmentBonesInMicroCTFilter.values()[0]
    else:
        filter_object = itk.SegmentBonesInMicroCTFilter

    segment_bones_in_micro_ct_filter.__doc__ = filter_object.__doc__
    segment_bones_in_micro_ct_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    segment_bones_in_micro_ct_filter.__doc__ += "Available Keyword Arguments:\n"
    segment_bones_in_micro_ct_filter.__doc__ += "".join([
        "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
        for item in dir(filter_object)
        if item[:3] == "Set"])



