version: 2

jobs:
  pep8:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e pep8
  py35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py35
  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py36
  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py37
  py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py38


workflows:
  version: 2

  test:
    jobs:
      - pep8
      - py35
      - py36
      - py37
      - py38
