[tool.poetry]
name = "kwonfig"
version = "0.2.3"
description = "Complete, extensible configuration manager"
authors = ["KokaKiwi <kokakiwi+git@kokakiwi.net>"]
license = "BSD-3-Clause"
homepage = "https://gitlab.kokakiwi.net/kokakiwi/kwonfig"
repository = "https://gitlab.kokakiwi.net/kokakiwi/kwonfig.git"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.6",
  "Topic :: Software Development",
  "Topic :: Utilities",
  "Typing :: Typed"
]
include = [
  "LICENSE"
]

[tool.poetry.urls]
"Issues" = "https://gitlab.kokakiwi.net/kokakiwi/kwonfig/-/issues"

[tool.poetry.dependencies]
python = "^3.6"

deepmerge = "^0.1"
loguru = "^0.5"
pluggy = "^0.13"

hjson = { version = "^3.0", optional = true }
ini-parser = { version = "^1.0", optional = true }
json5 = { version = "^0.9", optional = true }
pydantic = { version = "^1.4", optional = true }
qtoml = { version = "^0.3", optional = true }
"ruamel.yaml" = { version = "^0.16", optional = true }

[tool.poetry.dev-dependencies]
sphinx = "^3.0"
sphinxcontrib-trio = "^1.1"

[tool.poetry.extras]
all = [
  "hjson", "ini-parser", "json5", "qtoml", "ruamel.yaml",
  "pydantic",
]

ini = ["ini-parser"]
toml = ["qtoml"]
yaml = ["ruamel.yaml"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
