language: python
dist: xenial
cache: pip
env:
    matrix:
        - COVERALLS=true

install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade -r requirements-test.txt
    - pip install --upgrade .
before_script:
    - pytest --version
script:
    - pytest -vv --cov
after_success:
    - if [[ ${COVERALLS} == true ]]; then coveralls; fi

branches:
  only:
  - master
  - /^v(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/ # SemVer tags (https://github.com/semver/semver/issues/232#issuecomment-405596809)

jobs:
    fast_finish: true
    allow_failures:
        - python: "3.5-dev"
        - python: "3.6-dev"
        - python: "3.7-dev"
        - python: "3.8-dev"
    include:
        - python: "3.5"
        - python: "3.5-dev"
        - python: "3.6"
        - python: "3.6-dev"
        - python: "3.7"
        - python: "3.7-dev"
        - python: "3.8-dev"
          env: COVERALLS=false

        - stage: pylint
          python: "3.8"
          script:
            - python run_pylint.py --disable=fixme --fail-under=9.5 pysmiles
          after_success: skip

        - stage: deploy
          python: "3.8"
          env: COVERALLS=false
          before_script: skip
          script: skip
          deploy:
            provider: pypi
            user: pckroon
            password:
              secure: 2fE15bz83DqUJWKhyS/jl29T2Bdkfw6u/CfNOf4n9AXZwKUYfd4LYbxh3rWlhOWmxFDhaNStHdZvYddGIjHj5gvz7uMI7tB/2tx3t5FifqQ7OZqfxS69YsVRLl7H0Ty5oifSJBvrIGEbzM9KKQUrP/y/gcFK/hHJNV3n8eGof5+6PmKjwZxiI4uAHhmsK2U4J8PSg5RXNQxbvLNUgAPjYMn/GKIL/75+yEGO/5H2u+zokISjKTs1WAYD5dDIa89h+QD/WrMh9n+oLtjkvrtsj3RJnwKYs2qeHmdZSQe4KKmlR+pVBOA+Tlzp01a1uznk7LfwSUcSE9Fn7D6WbZEZaimEqxPKrEwNHDLfVi7Y/qXWRU9jqvOkInmTLB2hMWteg/0kqtGBV1KYaOCvYAHR7loiF6xtiY6uTWHsKyrC4T9Y9j9839FsQOGN7l2BJn404Hzao9RSksPSX9TfC9el0YfLwmS3WwsYDo4JD5EHmikTfD/ux2t64qwSS0m1rWVg5QYFz5lgEK0gVGDeq4iSo3ZXqiGn7aCLrTohId1uEVA4pgDaun2pZeTUCYHsO6BAGGnMcdahpN4DQtzB/B1pIgH1nbQ79fbwECxp/58JZ/aR9WvfZQB9G0yQH9tL1Sv4bo7W5HBj/aWNlKUznBw1tXGu5ECK0YucRsJvxFkI39g=
            on:
              tags: true

