[tool.poetry]
name = "synch"
version = "0.6.0"
description = "Sync data from other DB to ClickHouse, current support postgres and mysql, and support full and increment ETL."
authors = ["long2ice <long2ice@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/long2ice/synch"
repository = "https://github.com/long2ice/synch.git"
documentation = "https://github.com/long2ice/synch"
keywords = ["MySQL", "ClickHouse", "Sync"]
packages = [
    { include = "synch" }
]
include = ["CHANGELOG.md", "LICENSE", "README.md", "pyproject.toml"]

[tool.poetry.dependencies]
python = "^3.6"
mysql-replication = "*"
clickhouse-driver = "*"
redis = "*"
mysqlclient = "*"
sentry-sdk = "*"
python-dateutil = "*"
pydantic = "*"
sqlparse = "*"
kafka-python = "*"
psycopg2 = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
flake8 = "*"
isort = "*"
black = "^19.10b0"
pytest-xdist = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
synch = "synch.cli:cli"