[tool.poetry]
name = "brip"
version = "0.1.0"
description = ""
authors = ["Briana <allenbri25@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pydicom = "^2.0.0"
numpy = "^1.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
