language: python
python:
  - "2.7"
  - "3.6"

env:
  - GLPK_VERSION=4.65

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp3-dev
  - wget http://ftp.gnu.org/gnu/glpk/glpk-${GLPK_VERSION}.tar.gz
  - tar xzf glpk-${GLPK_VERSION}.tar.gz
  - pushd glpk-${GLPK_VERSION} && ./configure --prefix=/usr && make && sudo make install && popd

install:
  - pip install cpp-coveralls setuptools_scm tox-travis

script:
  - tox -v
  - pip install .
  - python examples/correlation.py
  - python examples/hamiltonian.py
  - python examples/maxflow.py
  - python examples/sat.py
  - python examples/sat2.py
  # skip this example for now
  #- python examples/threads.py

after_success:
  - coveralls --exclude-pattern 'glpk-*' --exclude tests --gcov-options '\-lp'

notifications:
  email:
    on_success: never
    on_failure: always
