language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -e .
  - pip install pycodestyle
  - pip install pylint
script: ./test.sh
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: "3.7"
