
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-25T12:17:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "01c72eedb2537fdc7035ab8c2977773b1b54a0f8",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
