---

- name: Post-run playbook for networking-ansible-tempest-ovs job
  hosts: controller
  tasks:
    - name: check if ansible log file exists
      stat:
        path: '{{ ansible_logs_file }}'
      register: logs_file

    - name: collect ansible logs
      copy:
        src: '{{ ansible_logs_file }}'
        dest: '{{ zuul.executor.log_root }}/ansible.log'
        remote_src: yes
      when: logs_file.stat.exists
