# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pdhttp
from pdhttp.api.freedrive_api import FreedriveApi  # noqa: E501
from pdhttp.rest import ApiException


class TestFreedriveApi(unittest.TestCase):
    """FreedriveApi unit test stubs"""

    def setUp(self):
        self.api = pdhttp.api.freedrive_api.FreedriveApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_zg_off(self):
        """Test case for zg_off

        Disable Freedrive Mode  # noqa: E501
        """
        pass

    def test_zg_on(self):
        """Test case for zg_on

        Enable Freedrive Mode  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
