# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pyaogmaneo
else:
    import _pyaogmaneo

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyaogmaneo.delete_SwigPyIterator

    def value(self):
        return _pyaogmaneo.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyaogmaneo.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyaogmaneo.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyaogmaneo.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyaogmaneo.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyaogmaneo.SwigPyIterator_copy(self)

    def next(self):
        return _pyaogmaneo.SwigPyIterator_next(self)

    def __next__(self):
        return _pyaogmaneo.SwigPyIterator___next__(self)

    def previous(self):
        return _pyaogmaneo.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyaogmaneo.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyaogmaneo.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyaogmaneo.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyaogmaneo.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyaogmaneo.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyaogmaneo.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyaogmaneo.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _pyaogmaneo:
_pyaogmaneo.SwigPyIterator_swigregister(SwigPyIterator)

class StdVeci(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVeci_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVeci___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVeci___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVeci___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVeci___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVeci___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVeci___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVeci___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVeci___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVeci___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVeci_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVeci_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVeci_empty(self)

    def size(self):
        return _pyaogmaneo.StdVeci_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVeci_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVeci_begin(self)

    def end(self):
        return _pyaogmaneo.StdVeci_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVeci_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVeci_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVeci_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVeci_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVeci_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVeci_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVeci_swiginit(self, _pyaogmaneo.new_StdVeci(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVeci_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVeci_front(self)

    def back(self):
        return _pyaogmaneo.StdVeci_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVeci_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVeci_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVeci_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVeci_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVeci_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVeci

# Register StdVeci in _pyaogmaneo:
_pyaogmaneo.StdVeci_swigregister(StdVeci)

class StdVec2Di(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVec2Di_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVec2Di___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVec2Di___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVec2Di___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVec2Di___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVec2Di___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVec2Di___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVec2Di___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVec2Di___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVec2Di___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVec2Di_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVec2Di_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVec2Di_empty(self)

    def size(self):
        return _pyaogmaneo.StdVec2Di_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVec2Di_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVec2Di_begin(self)

    def end(self):
        return _pyaogmaneo.StdVec2Di_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVec2Di_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVec2Di_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVec2Di_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVec2Di_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVec2Di_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVec2Di_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVec2Di_swiginit(self, _pyaogmaneo.new_StdVec2Di(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVec2Di_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVec2Di_front(self)

    def back(self):
        return _pyaogmaneo.StdVec2Di_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVec2Di_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVec2Di_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVec2Di_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVec2Di_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVec2Di_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVec2Di

# Register StdVec2Di in _pyaogmaneo:
_pyaogmaneo.StdVec2Di_swigregister(StdVec2Di)

class StdVecf(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVecf_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVecf___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVecf___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVecf___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVecf___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVecf___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVecf___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVecf___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVecf___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVecf___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVecf_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVecf_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVecf_empty(self)

    def size(self):
        return _pyaogmaneo.StdVecf_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVecf_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVecf_begin(self)

    def end(self):
        return _pyaogmaneo.StdVecf_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVecf_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVecf_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVecf_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVecf_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVecf_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVecf_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVecf_swiginit(self, _pyaogmaneo.new_StdVecf(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVecf_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVecf_front(self)

    def back(self):
        return _pyaogmaneo.StdVecf_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVecf_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVecf_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVecf_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVecf_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVecf_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVecf

# Register StdVecf in _pyaogmaneo:
_pyaogmaneo.StdVecf_swigregister(StdVecf)

class StdVec2Df(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVec2Df_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVec2Df___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVec2Df___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVec2Df___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVec2Df___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVec2Df___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVec2Df___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVec2Df___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVec2Df___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVec2Df___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVec2Df_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVec2Df_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVec2Df_empty(self)

    def size(self):
        return _pyaogmaneo.StdVec2Df_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVec2Df_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVec2Df_begin(self)

    def end(self):
        return _pyaogmaneo.StdVec2Df_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVec2Df_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVec2Df_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVec2Df_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVec2Df_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVec2Df_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVec2Df_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVec2Df_swiginit(self, _pyaogmaneo.new_StdVec2Df(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVec2Df_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVec2Df_front(self)

    def back(self):
        return _pyaogmaneo.StdVec2Df_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVec2Df_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVec2Df_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVec2Df_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVec2Df_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVec2Df_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVec2Df

# Register StdVec2Df in _pyaogmaneo:
_pyaogmaneo.StdVec2Df_swigregister(StdVec2Df)

class StdVecuchar(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVecuchar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVecuchar___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVecuchar___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVecuchar___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVecuchar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVecuchar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVecuchar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVecuchar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVecuchar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVecuchar___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVecuchar_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVecuchar_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVecuchar_empty(self)

    def size(self):
        return _pyaogmaneo.StdVecuchar_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVecuchar_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVecuchar_begin(self)

    def end(self):
        return _pyaogmaneo.StdVecuchar_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVecuchar_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVecuchar_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVecuchar_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVecuchar_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVecuchar_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVecuchar_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVecuchar_swiginit(self, _pyaogmaneo.new_StdVecuchar(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVecuchar_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVecuchar_front(self)

    def back(self):
        return _pyaogmaneo.StdVecuchar_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVecuchar_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVecuchar_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVecuchar_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVecuchar_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVecuchar_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVecuchar

# Register StdVecuchar in _pyaogmaneo:
_pyaogmaneo.StdVecuchar_swigregister(StdVecuchar)

class StdVec2Duchar(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVec2Duchar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVec2Duchar___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVec2Duchar___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVec2Duchar___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVec2Duchar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVec2Duchar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVec2Duchar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVec2Duchar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVec2Duchar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVec2Duchar___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVec2Duchar_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVec2Duchar_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVec2Duchar_empty(self)

    def size(self):
        return _pyaogmaneo.StdVec2Duchar_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVec2Duchar_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVec2Duchar_begin(self)

    def end(self):
        return _pyaogmaneo.StdVec2Duchar_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVec2Duchar_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVec2Duchar_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVec2Duchar_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVec2Duchar_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVec2Duchar_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVec2Duchar_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVec2Duchar_swiginit(self, _pyaogmaneo.new_StdVec2Duchar(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVec2Duchar_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVec2Duchar_front(self)

    def back(self):
        return _pyaogmaneo.StdVec2Duchar_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVec2Duchar_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVec2Duchar_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVec2Duchar_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVec2Duchar_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVec2Duchar_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVec2Duchar

# Register StdVec2Duchar in _pyaogmaneo:
_pyaogmaneo.StdVec2Duchar_swigregister(StdVec2Duchar)

class StdVecInt3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVecInt3_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVecInt3___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVecInt3___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVecInt3___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVecInt3___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVecInt3___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVecInt3___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVecInt3___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVecInt3___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVecInt3___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVecInt3_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVecInt3_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVecInt3_empty(self)

    def size(self):
        return _pyaogmaneo.StdVecInt3_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVecInt3_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVecInt3_begin(self)

    def end(self):
        return _pyaogmaneo.StdVecInt3_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVecInt3_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVecInt3_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVecInt3_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVecInt3_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVecInt3_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVecInt3_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVecInt3_swiginit(self, _pyaogmaneo.new_StdVecInt3(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVecInt3_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVecInt3_front(self)

    def back(self):
        return _pyaogmaneo.StdVecInt3_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVecInt3_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVecInt3_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVecInt3_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVecInt3_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVecInt3_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVecInt3

# Register StdVecInt3 in _pyaogmaneo:
_pyaogmaneo.StdVecInt3_swigregister(StdVecInt3)

class StdVecLayerDesc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVecLayerDesc_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVecLayerDesc___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVecLayerDesc___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVecLayerDesc___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVecLayerDesc___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVecLayerDesc___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVecLayerDesc___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVecLayerDesc___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVecLayerDesc___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVecLayerDesc___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVecLayerDesc_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVecLayerDesc_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVecLayerDesc_empty(self)

    def size(self):
        return _pyaogmaneo.StdVecLayerDesc_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVecLayerDesc_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVecLayerDesc_begin(self)

    def end(self):
        return _pyaogmaneo.StdVecLayerDesc_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVecLayerDesc_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVecLayerDesc_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVecLayerDesc_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVecLayerDesc_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVecLayerDesc_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVecLayerDesc_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVecLayerDesc_swiginit(self, _pyaogmaneo.new_StdVecLayerDesc(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVecLayerDesc_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVecLayerDesc_front(self)

    def back(self):
        return _pyaogmaneo.StdVecLayerDesc_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVecLayerDesc_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVecLayerDesc_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVecLayerDesc_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVecLayerDesc_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVecLayerDesc_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVecLayerDesc

# Register StdVecLayerDesc in _pyaogmaneo:
_pyaogmaneo.StdVecLayerDesc_swigregister(StdVecLayerDesc)

class StdVecImageEncoderVisibleLayerDesc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___nonzero__(self)

    def __bool__(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___bool__(self)

    def __len__(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___len__(self)

    def __getslice__(self, i, j):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc___setitem__(self, *args)

    def pop(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_pop(self)

    def append(self, x):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_append(self, x)

    def empty(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_empty(self)

    def size(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_size(self)

    def swap(self, v):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_swap(self, v)

    def begin(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_begin(self)

    def end(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_end(self)

    def rbegin(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_rbegin(self)

    def rend(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_rend(self)

    def clear(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_clear(self)

    def get_allocator(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_get_allocator(self)

    def pop_back(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_pop_back(self)

    def erase(self, *args):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_erase(self, *args)

    def __init__(self, *args):
        _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_swiginit(self, _pyaogmaneo.new_StdVecImageEncoderVisibleLayerDesc(*args))

    def push_back(self, x):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_push_back(self, x)

    def front(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_front(self)

    def back(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_back(self)

    def assign(self, n, x):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_assign(self, n, x)

    def resize(self, *args):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_resize(self, *args)

    def insert(self, *args):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_insert(self, *args)

    def reserve(self, n):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_reserve(self, n)

    def capacity(self):
        return _pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_capacity(self)
    __swig_destroy__ = _pyaogmaneo.delete_StdVecImageEncoderVisibleLayerDesc

# Register StdVecImageEncoderVisibleLayerDesc in _pyaogmaneo:
_pyaogmaneo.StdVecImageEncoderVisibleLayerDesc_swigregister(StdVecImageEncoderVisibleLayerDesc)

class Int3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_pyaogmaneo.Int3_x_get, _pyaogmaneo.Int3_x_set)
    y = property(_pyaogmaneo.Int3_y_get, _pyaogmaneo.Int3_y_set)
    z = property(_pyaogmaneo.Int3_z_get, _pyaogmaneo.Int3_z_set)

    def __init__(self, *args):
        _pyaogmaneo.Int3_swiginit(self, _pyaogmaneo.new_Int3(*args))
    __swig_destroy__ = _pyaogmaneo.delete_Int3

# Register Int3 in _pyaogmaneo:
_pyaogmaneo.Int3_swigregister(Int3)


def setNumThreads(numThreads):
    return _pyaogmaneo.setNumThreads(numThreads)

def getNumThreads():
    return _pyaogmaneo.getNumThreads()
class LayerDesc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hiddenSize = property(_pyaogmaneo.LayerDesc_hiddenSize_get, _pyaogmaneo.LayerDesc_hiddenSize_set)
    ffRadius = property(_pyaogmaneo.LayerDesc_ffRadius_get, _pyaogmaneo.LayerDesc_ffRadius_set)
    pRadius = property(_pyaogmaneo.LayerDesc_pRadius_get, _pyaogmaneo.LayerDesc_pRadius_set)
    aRadius = property(_pyaogmaneo.LayerDesc_aRadius_get, _pyaogmaneo.LayerDesc_aRadius_set)
    ticksPerUpdate = property(_pyaogmaneo.LayerDesc_ticksPerUpdate_get, _pyaogmaneo.LayerDesc_ticksPerUpdate_set)
    temporalHorizon = property(_pyaogmaneo.LayerDesc_temporalHorizon_get, _pyaogmaneo.LayerDesc_temporalHorizon_set)
    historyCapacity = property(_pyaogmaneo.LayerDesc_historyCapacity_get, _pyaogmaneo.LayerDesc_historyCapacity_set)

    def __init__(self, *args):
        _pyaogmaneo.LayerDesc_swiginit(self, _pyaogmaneo.new_LayerDesc(*args))
    __swig_destroy__ = _pyaogmaneo.delete_LayerDesc

# Register LayerDesc in _pyaogmaneo:
_pyaogmaneo.LayerDesc_swigregister(LayerDesc)
cvar = _pyaogmaneo.cvar
inputTypeNone = cvar.inputTypeNone
inputTypePrediction = cvar.inputTypePrediction
inputTypeAction = cvar.inputTypeAction

class Hierarchy(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyaogmaneo.Hierarchy_swiginit(self, _pyaogmaneo.new_Hierarchy(*args))

    def save(self, name):
        return _pyaogmaneo.Hierarchy_save(self, name)

    def step(self, inputCs, learnEnabled=True, reward=0.0, mimic=False):
        return _pyaogmaneo.Hierarchy_step(self, inputCs, learnEnabled, reward, mimic)

    def getNumLayers(self):
        return _pyaogmaneo.Hierarchy_getNumLayers(self)

    def getPredictionCs(self, i):
        return _pyaogmaneo.Hierarchy_getPredictionCs(self, i)

    def getUpdate(self, l):
        return _pyaogmaneo.Hierarchy_getUpdate(self, l)

    def getHiddenCs(self, l):
        return _pyaogmaneo.Hierarchy_getHiddenCs(self, l)

    def getHiddenSize(self, l):
        return _pyaogmaneo.Hierarchy_getHiddenSize(self, l)

    def getTicks(self, l):
        return _pyaogmaneo.Hierarchy_getTicks(self, l)

    def getTicksPerUpdate(self, l):
        return _pyaogmaneo.Hierarchy_getTicksPerUpdate(self, l)

    def getNumSCVisibleLayers(self, l):
        return _pyaogmaneo.Hierarchy_getNumSCVisibleLayers(self, l)

    def getNumInputs(self):
        return _pyaogmaneo.Hierarchy_getNumInputs(self)

    def getInputSize(self, i):
        return _pyaogmaneo.Hierarchy_getInputSize(self, i)

    def pLayerExists(self, l, v):
        return _pyaogmaneo.Hierarchy_pLayerExists(self, l, v)

    def aLayerExists(self, v):
        return _pyaogmaneo.Hierarchy_aLayerExists(self, v)

    def setSCAlpha(self, l, alpha):
        return _pyaogmaneo.Hierarchy_setSCAlpha(self, l, alpha)

    def getSCAlpha(self, l):
        return _pyaogmaneo.Hierarchy_getSCAlpha(self, l)

    def setPAlpha(self, l, v, alpha):
        return _pyaogmaneo.Hierarchy_setPAlpha(self, l, v, alpha)

    def getPAlpha(self, l, v):
        return _pyaogmaneo.Hierarchy_getPAlpha(self, l, v)

    def setPTargetRange(self, l, v, targetRange):
        return _pyaogmaneo.Hierarchy_setPTargetRange(self, l, v, targetRange)

    def getPTargetRange(self, l, v):
        return _pyaogmaneo.Hierarchy_getPTargetRange(self, l, v)

    def setAAlpha(self, v, alpha):
        return _pyaogmaneo.Hierarchy_setAAlpha(self, v, alpha)

    def getAAlpha(self, v):
        return _pyaogmaneo.Hierarchy_getAAlpha(self, v)

    def setABeta(self, v, beta):
        return _pyaogmaneo.Hierarchy_setABeta(self, v, beta)

    def getABeta(self, v):
        return _pyaogmaneo.Hierarchy_getABeta(self, v)

    def setAGamma(self, v, gamma):
        return _pyaogmaneo.Hierarchy_setAGamma(self, v, gamma)

    def getAGamma(self, v):
        return _pyaogmaneo.Hierarchy_getAGamma(self, v)

    def setAMinSteps(self, v, minSteps):
        return _pyaogmaneo.Hierarchy_setAMinSteps(self, v, minSteps)

    def getAMinSteps(self, v):
        return _pyaogmaneo.Hierarchy_getAMinSteps(self, v)

    def setAHistoryIters(self, v, historyIters):
        return _pyaogmaneo.Hierarchy_setAHistoryIters(self, v, historyIters)

    def getAHistoryIters(self, v):
        return _pyaogmaneo.Hierarchy_getAHistoryIters(self, v)
    __swig_destroy__ = _pyaogmaneo.delete_Hierarchy

# Register Hierarchy in _pyaogmaneo:
_pyaogmaneo.Hierarchy_swigregister(Hierarchy)

class ImageEncoderVisibleLayerDesc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    size = property(_pyaogmaneo.ImageEncoderVisibleLayerDesc_size_get, _pyaogmaneo.ImageEncoderVisibleLayerDesc_size_set)
    radius = property(_pyaogmaneo.ImageEncoderVisibleLayerDesc_radius_get, _pyaogmaneo.ImageEncoderVisibleLayerDesc_radius_set)

    def __init__(self, *args):
        _pyaogmaneo.ImageEncoderVisibleLayerDesc_swiginit(self, _pyaogmaneo.new_ImageEncoderVisibleLayerDesc(*args))
    __swig_destroy__ = _pyaogmaneo.delete_ImageEncoderVisibleLayerDesc

# Register ImageEncoderVisibleLayerDesc in _pyaogmaneo:
_pyaogmaneo.ImageEncoderVisibleLayerDesc_swigregister(ImageEncoderVisibleLayerDesc)

class ImageEncoder(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    alpha = property(_pyaogmaneo.ImageEncoder_alpha_get, _pyaogmaneo.ImageEncoder_alpha_set)
    gamma = property(_pyaogmaneo.ImageEncoder_gamma_get, _pyaogmaneo.ImageEncoder_gamma_set)

    def __init__(self, *args):
        _pyaogmaneo.ImageEncoder_swiginit(self, _pyaogmaneo.new_ImageEncoder(*args))

    def save(self, name):
        return _pyaogmaneo.ImageEncoder_save(self, name)

    def step(self, inputs, learnEnabled=True):
        return _pyaogmaneo.ImageEncoder_step(self, inputs, learnEnabled)

    def reconstruct(self, reconCs):
        return _pyaogmaneo.ImageEncoder_reconstruct(self, reconCs)

    def getNumVisibleLayers(self):
        return _pyaogmaneo.ImageEncoder_getNumVisibleLayers(self)

    def getReconstruction(self, i):
        return _pyaogmaneo.ImageEncoder_getReconstruction(self, i)

    def getHiddenCs(self):
        return _pyaogmaneo.ImageEncoder_getHiddenCs(self)

    def getHiddenSize(self):
        return _pyaogmaneo.ImageEncoder_getHiddenSize(self)

    def getVisibleSize(self, i):
        return _pyaogmaneo.ImageEncoder_getVisibleSize(self, i)
    __swig_destroy__ = _pyaogmaneo.delete_ImageEncoder

# Register ImageEncoder in _pyaogmaneo:
_pyaogmaneo.ImageEncoder_swigregister(ImageEncoder)



