
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-02T12:18:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bcbb9a8a16b457572da9514b4e90944b2667c7a",
 "version": "0.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
