name: session_list
author: Arnaud Kientz
email: arnaud@unpeud.info
url: https://ajenti.org
version: '0.3'
title: 'Session list'
icon: network-wired
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
resources:
    - resources/js/module.es
    - resources/js/routing.es
    - resources/js/controllers/index.controller.coffee
    - resources/js/controllers/widget.controller.es
    - resources/partial/index.html
    - resources/partial/widget.html
    - ng:ajenti.session_list
