[tool.poetry]
name = "django_htmx"
version = "0.1.2"
description = ""
authors = ["nicokant <niccolocantu@gmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.6"
django = ">=2.2 || ^3.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
