# coding: utf-8

"""
    clusterapis.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kaistack.clients.openapi_clients.cluster.configuration import Configuration


class CodegenClusterConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'artifacts_store': 'CodegenArtifactsStoreConfig'
    }

    attribute_map = {
        'artifacts_store': 'artifactsStore'
    }

    def __init__(self, artifacts_store=None, local_vars_configuration=None):  # noqa: E501
        """CodegenClusterConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._artifacts_store = None
        self.discriminator = None

        if artifacts_store is not None:
            self.artifacts_store = artifacts_store

    @property
    def artifacts_store(self):
        """Gets the artifacts_store of this CodegenClusterConfig.  # noqa: E501


        :return: The artifacts_store of this CodegenClusterConfig.  # noqa: E501
        :rtype: CodegenArtifactsStoreConfig
        """
        return self._artifacts_store

    @artifacts_store.setter
    def artifacts_store(self, artifacts_store):
        """Sets the artifacts_store of this CodegenClusterConfig.


        :param artifacts_store: The artifacts_store of this CodegenClusterConfig.  # noqa: E501
        :type: CodegenArtifactsStoreConfig
        """

        self._artifacts_store = artifacts_store

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodegenClusterConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CodegenClusterConfig):
            return True

        return self.to_dict() != other.to_dict()
