# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from spaceone.api.inventory.v1 import ip_address_pb2 as spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2


class IPAddressStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.allocate = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/allocate',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.AllocateIPRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
                )
        self.reserve = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/reserve',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.ReserveIPRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
                )
        self.release = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/release',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.update = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/update',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.UpdateIPRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
                )
        self.pin_data = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/pin_data',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.PinIPDataRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
                )
        self.get = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/get',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.GetIPRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
                )
        self.list = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/list',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPQuery.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPsInfo.FromString,
                )
        self.stat = channel.unary_unary(
                '/spaceone.api.inventory.v1.IPAddress/stat',
                request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPStatQuery.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                )


class IPAddressServicer(object):
    """Missing associated documentation comment in .proto file"""

    def allocate(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reserve(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def release(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pin_data(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stat(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IPAddressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'allocate': grpc.unary_unary_rpc_method_handler(
                    servicer.allocate,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.AllocateIPRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.SerializeToString,
            ),
            'reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.reserve,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.ReserveIPRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.SerializeToString,
            ),
            'release': grpc.unary_unary_rpc_method_handler(
                    servicer.release,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.UpdateIPRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.SerializeToString,
            ),
            'pin_data': grpc.unary_unary_rpc_method_handler(
                    servicer.pin_data,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.PinIPDataRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.GetIPRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.SerializeToString,
            ),
            'list': grpc.unary_unary_rpc_method_handler(
                    servicer.list,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPQuery.FromString,
                    response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPsInfo.SerializeToString,
            ),
            'stat': grpc.unary_unary_rpc_method_handler(
                    servicer.stat,
                    request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPStatQuery.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceone.api.inventory.v1.IPAddress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IPAddress(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def allocate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/allocate',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.AllocateIPRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/reserve',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.ReserveIPRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/release',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/update',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.UpdateIPRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pin_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/pin_data',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.PinIPDataRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/get',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.GetIPRequest.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/list',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPQuery.SerializeToString,
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPsInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.inventory.v1.IPAddress/stat',
            spaceone_dot_api_dot_inventory_dot_v1_dot_ip__address__pb2.IPStatQuery.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
