[tool.poetry]
name = "devyzer"
version = "0.1.1a2"
description = "Devyzer Cli: a cli that connects to devyzer to enable developers using cli intelligently in addition to native devyzer featuers"
authors = ["Ayham Hassan <ayham@devyzer.io>"]

[tool.poetry.dependencies]
python = "^3.6"
briefcase = "^0.3.0"
prompt-toolkit = "2.0.10"
click = "7.1.2"
pygments = "2.5.2"
GitPython = "3.1.1"
halo = "0.0.28"
questionary = "1.4.0"
pyfiglet = "0.8.post1"
requests = "2.23.0"
yaspin = "0.15.0"
six = "1.14.0"
ordereddict = "1.1"
configobj = "5.0.6"
python-socketio = "4.0.0"
tornado = "^6.0.4"
python-dotenv = "^0.13.0"

[tool.poetry.dev-dependencies]
pyinstaller = "^3.6"
nuitka = "^0.6.7"
wheel = "^0.34.2"



[tool.poetry.scripts]
devyzer = "devyzer.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

