from ._confusion_matrix import plot_confusion_matrix
from ._missing_value import plot_missing_value
from ._svc_decision import plot_svc
from ._residual_plot import plot_residual
from ._actual_vs_prediction import plot_actual_vs_prediction
from ._correlation_matrix import plot_correlation_matrix
from ._association_matrix import plot_association_matrix
from ._classification_report import plot_classification_report
from ._correlation_ratio import plot_correlation_ratio
from ._roc_curve import plot_roc_curve
from ._pr_curve import plot_pr_curve
