
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-25T13:46:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc6009ad93df90c9ce085cfd9cb5ec48440844ea",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
