# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_create_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='tle_source',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
