
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-24T15:26:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b20798de7bb37c2cb48a51656d9ad6aeef8e8bc",
 "version": "0.7.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
