
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-29T08:59:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2618de59a400392a0217d2ff4d088cb4f0f4c68b",
 "version": "0.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
