os: linux
dist: xenial
services:
  - mysql
  - postgresql
language: python
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "3.8"
  - "3.7"
  - "3.6"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_testing
  - KOTTI_TEST_DB_STRING=mysql+mysqldb://root@localhost:3306/kotti_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - travis_retry pip install -U pip wheel setuptools
  - travis_retry pip install psycopg2-binary mysqlclient python-coveralls codecov
  - travis_retry pip install -e ".[testing]"
before_script:
  - psql -c 'create database kotti_testing;' -U postgres
  - mysql -e 'create database kotti_testing;'
script:
  - py.test -rw --tb=native --cov=kotti --cov-report=term-missing
after_success:
  - coveralls
  - codecov
notifications:
  irc: "irc.freenode.org#kotti"
  email: false
