# Automatic file, do not edit!

from makeblock import cyberpi

goto_offline_mode = cyberpi.goto_offline_mode
goto_online_mode = cyberpi.goto_online_mode


set_recognition_url=cyberpi.set_recognition_url
get_mac_address=cyberpi.get_mac_address
get_battery=cyberpi.get_battery
get_firmware_version=cyberpi.get_firmware_version
get_ble=cyberpi.get_ble
get_name=cyberpi.get_name
set_name=cyberpi.set_name
get_brightness=cyberpi.get_brightness
get_bri=cyberpi.get_bri
get_loudness=cyberpi.get_loudness
is_tiltback=cyberpi.is_tiltback
is_tiltforward=cyberpi.is_tiltforward
is_tiltleft=cyberpi.is_tiltleft
is_tiltright=cyberpi.is_tiltright
is_faceup=cyberpi.is_faceup
is_facedown=cyberpi.is_facedown
is_stand=cyberpi.is_stand
is_handstand=cyberpi.is_handstand
is_shake=cyberpi.is_shake
is_waveup=cyberpi.is_waveup
is_wavedown=cyberpi.is_wavedown
is_waveleft=cyberpi.is_waveleft
is_waveright=cyberpi.is_waveright
is_freefall=cyberpi.is_freefall
is_clockwise=cyberpi.is_clockwise
is_anticlockwise=cyberpi.is_anticlockwise
get_shakeval=cyberpi.get_shakeval
get_wave_angle=cyberpi.get_wave_angle
get_wave_speed=cyberpi.get_wave_speed
get_roll=cyberpi.get_roll
get_pitch=cyberpi.get_pitch
get_yaw=cyberpi.get_yaw
reset_yaw=cyberpi.reset_yaw
get_acc=cyberpi.get_acc
get_gyro=cyberpi.get_gyro
get_rotation=cyberpi.get_rotation
reset_rotation=cyberpi.reset_rotation
controller=cyberpi.controller
audio=cyberpi.audio
display=cyberpi.display
console=cyberpi.console
chart=cyberpi.chart
linechart=cyberpi.linechart
barchart=cyberpi.barchart
table=cyberpi.table
led=cyberpi.led
wifi=cyberpi.wifi
cloud=cyberpi.cloud
timer=cyberpi.timer
broadcast=cyberpi.broadcast
broadcast_and_wait=cyberpi.broadcast_and_wait
wifi_broadcast=cyberpi.wifi_broadcast
upload_broadcast=cyberpi.upload_broadcast
cloud_broadcast=cyberpi.cloud_broadcast
pocket=cyberpi.pocket
button=cyberpi.button
angle_sensor=cyberpi.angle_sensor
slider=cyberpi.slider
joystick=cyberpi.joystick
multi_touch=cyberpi.multi_touch
light_sensor=cyberpi.light_sensor
dual_rgb_sensor=cyberpi.dual_rgb_sensor
sound_sensor=cyberpi.sound_sensor
pir=cyberpi.pir
ultrasonic=cyberpi.ultrasonic
ranging_sensor=cyberpi.ranging_sensor
motion_sensor=cyberpi.motion_sensor
soil_sensor=cyberpi.soil_sensor
temp_sensor=cyberpi.temp_sensor
humiture=cyberpi.humiture
mq2=cyberpi.mq2
flame_sensor=cyberpi.flame_sensor
magnetic_sensor=cyberpi.magnetic_sensor
led_matrix=cyberpi.led_matrix
rgb_led=cyberpi.rgb_led
led_driver=cyberpi.led_driver
servo_driver=cyberpi.servo_driver
motor_driver=cyberpi.motor_driver
speaker=cyberpi.speaker
