
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-23T12:19:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "63e9cfa6a0ab7a5c6b8f4fd98100881f92f086dd",
 "version": "1.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
