
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-02T11:28:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "92c9e4a341ddcb073fcffcf4795c333d4e3646f0",
 "version": "0.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
