[tool.poetry]
name = "fatlib"
version = "0.1.0"
description = ""
authors = ["Code4Thought <support@code4thought.eu>"]

[tool.poetry.dependencies]
python = "^3.7"
scikit-learn = "^0.23.1"
pandas = "^1.0.5"
aif360 = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
isort = "^4.3.21"
flake8 = "^3.8.3"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
