[tool.poetry]
name = "lambda-generator"
version = "0.1.0"
description = ""
authors = ["matheusfrancisco <matheusmachadoufsc@gmail.com>", 
            "tiago.espanha <tiago.espanha@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "5.3.1"
yamllint = "^1.23.0"
sentry_sdk = "^0.15.0"
python-decouple = "^3.3"
typer = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
flake8 = "^3.8.3"
mock = "^4.0.2"

[tool.poetry.scripts]
lambda = "lambda_generator.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
