[tool.poetry]
name = "pybricks"
version = "2.0.0"
description = "Documentation and user-API stubs for Pybricks MicroPython"
authors = ["The Pybricks Authors <dev@pybricks.com>"]
maintainers = ["Laurens Valk <laurens@pybricks.com>", "David Lechner <david@pybricks.com>" ]
license = "MIT"
readme = "README.rst"
homepage = "https://pybricks.com"
repository = "https://github.com/pybricks/pybricks-api"
documentation = "https://docs.pybricks.com"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: Implementation :: MicroPython",
]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
doc8 = "*"
flake8 = "*"
sphinx = "==1.7.9"
sphinx-rtd-theme = "==0.4.3"
sphinxcontrib-contentui = "==0.2.2"
toml = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
