version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.8
jobs:
  test-3.6: &test-template
    environment:
      COLUMNS: 160
      # default is /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install deps
          command: |
            echo PATH=$PATH
            pip install -q --user --upgrade -r requirements.txt

      - run:
          name: List deps
          command: |
            mkdir -p artifacts
            pip freeze | tee artifacts/pip-freeze.txt
            pipdeptree | tee artifacts/pipdeptree.txt


      - run:
          name: setup.py develop
          command: |
            python setup.py develop --prefix ~/.local --no-deps

      - run:
          name: Run tests
          command: |
            make test

      - store_artifacts:
          path: cover
          destination: coverage

      - store_artifacts:
          path: notebooks
          destination: notebooks


  test-3.7:
    <<: *test-template
    docker:
    - image: python:3.7

  test-3.8:
    <<: *test-template
    docker:
    - image: python:3.8
