repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: [toml]
        language_version: python3.8

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.5.2
    hooks:
    -   id: pylint


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.9.0
    hooks:
    -   id: setup-cfg-fmt

  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: f4c4ac5948aff384af2b439bfabb2bdd65d2b3ac
    hooks:
    -   id: clang-format
