---
comment: false
coverage:
    status:
        patch:
            default:
                target: "100"
                paths:
                  - "tests/"
                  - "src/"
        project:
            default:
                target: "100"
                paths:
                  - "tests/"
                  - "src/"
