language: python

install:
  - pip install .
  - pip install pycodestyle

python:
  - "2.7"
  - "3.6"

script:
  - python -m unittest discover
  - pycodestyle pynetbox
  - pycodestyle --ignore=E501 tests

jobs:
  include:
    - stage: pypi release
      python: 2.7
      script: echo "Deploying to PyPI..."
      deploy:
        - provider: pypi
          distributions: sdist
          server: https://upload.pypi.org/legacy/
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            branch: master
            tags: true
