
# Default broker URL connecting to a local RabbitMQ instance for testing.
# Set this to a specific vhost in deployed instance.
amqp_url = "amqp://"

# All these three configs are for receiving messages from fedora-messaging.
# Set them to specific certificate and key file in deployed instance.
# [tls]
# ca_cert = "/etc/fedora-messaging/cacert.pem"
# keyfile = "/etc/fedora-messaging/fedora-key.pem"
# certfile = "/etc/fedora-messaging/fedora-cert.pem"

[client_properties]
app = "Message Tagging Service"
# Some suggested extra fields:
# URL of the project that provides this consumer
app_url = "https://github.com/fedora-modularity/message-tagging-service"
# Contact emails for the maintainer(s) of the consumer - in case the
# broker admin needs to contact them, for e.g.
app_contacts_email = ["cqi@redhat.com"]

[exchanges."amq.topic"]
type = "topic"
durable = true
auto_delete = false
arguments = {}

[queues.8bbfbdd1-02c1-4d18-a0ee-1752da519a17]
durable = false
auto_delete = true
exclusive = true
arguments = {}

[[bindings]]
queue = "8bbfbdd1-02c1-4d18-a0ee-1752da519a17"
exchange = "amq.topic"
routing_keys = ["org.fedoraproject.*.mbs.build.state.change"]

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(levelname)s %(name)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.twisted]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.pika]
level = "WARNING"
propagate = false
handlers = ["console"]

[log_config.root]
level = "ERROR"
handlers = ["console"]
