[tool.poetry]
name = "markovgram"
version = "0.3.5"
description = "Parse GDPR-exported Telegram data and create markovify Texts"
authors = ["Stefano Pigozzi <ste.pigozzi@gmail.com>"]
license = "AGPL-3.0+"

[tool.poetry.dependencies]
python = "^3.8"
markovify = "^0.7.2"
click = "^7.0"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
"markovgram" = 'markovgram.__main__:main'
"markovgram-merge" = 'markovgram.merge:run'
"markovgram-preview" = 'markovgram.preview:run'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
