
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-24T16:57:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "930656c062e6d0424dd0292f5cb09865fec3e1aa",
 "version": "1.6.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
