[tool.poetry]
name = "module-test-poetry"
version = "1.0.0"
description = ""
authors = ["Damiano Carradori <carradori@igenius.ai>"]

[tool.poetry.dependencies]
python = "^3.7"
ulid-py = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
