
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-01T14:43:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1f581b7ffcd5d8f3ae6c1c654d813a6641410eb",
 "version": "0.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
